In [1]:
##
import numpy as np
import time
import os, sys, importlib
#
import GalaxyEmu
#
import cleaner

2025-05-29 11:18:38.867770: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-05-29 11:18:38.871658: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-05-29 11:18:38.926365: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-05-29 11:18:39.623747: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
#Avoid tensorflow Warning messages
import logging
logging.getLogger('tensorflow').disabled = True

In [3]:
emu = GalaxyEmu.GalaxyEmu( emulator_ID = 0, emulator_version=2, extra = '20Mpc')

2025-05-29 11:18:40.179706: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2251] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [4]:
test_param = np.array([ 1.59511064, -0.7121721 ,  1.45046387, -1.3652633 ,  0.59055863, 
                      0.8159, 0.3089, 0.0486, 0.9667, 0.6774, 0, -2.5, 1])

In [5]:
#Speed Performance

In [6]:
%%time
for i in range(1000):
    emu.get_clustering(test_param)

CPU times: user 25.4 s, sys: 542 ms, total: 26 s
Wall time: 24.5 s


In [7]:
# 1000 cases in 24.5 seconds in this Computer

In [8]:
N = 1000000
test_param2 = np.zeros((N,len(test_param))) + np.atleast_2d(test_param)

In [9]:
%%time
emu.get_clustering(test_param2)

CPU times: user 21.4 s, sys: 16.3 s, total: 37.7 s
Wall time: 1.92 s


array([[2.34859058e+02, 1.90084219e+02, 1.47299900e+02, ...,
        1.14658552e+00, 3.80754183e-01, 1.82949944e-01],
       [2.34859058e+02, 1.90084219e+02, 1.47299900e+02, ...,
        1.14658552e+00, 3.80754183e-01, 1.82949944e-01],
       [2.34859058e+02, 1.90084219e+02, 1.47299900e+02, ...,
        1.14658552e+00, 3.80754183e-01, 1.82949944e-01],
       ...,
       [2.34859058e+02, 1.90084219e+02, 1.47299900e+02, ...,
        1.14658552e+00, 3.80754183e-01, 1.82949944e-01],
       [2.34859058e+02, 1.90084219e+02, 1.47299900e+02, ...,
        1.14658552e+00, 3.80754183e-01, 1.82949944e-01],
       [2.34859058e+02, 1.90084219e+02, 1.47299900e+02, ...,
        1.14658552e+00, 3.80754183e-01, 1.82949944e-01]])

In [10]:
# 1000000 cases in 1.9 seconds in this Computer [Vectorize test]

In [11]:
#################### Emulator test ###########################

In [12]:
#Emulators

In [13]:
#wp
emu_wp   = GalaxyEmu.GalaxyEmu( emulator_ID = 0, emulator_version=2, extra = '20Mpc')
#xil0
emu_xil0 = GalaxyEmu.GalaxyEmu( emulator_ID = 1, emulator_version=2)
#xil0
emu_xil2 = GalaxyEmu.GalaxyEmu( emulator_ID = 2, emulator_version=2)
#xil0
emu_xil4 = GalaxyEmu.GalaxyEmu( emulator_ID = 3, emulator_version=2)
#delta sigma [long integration]
emu_ds = GalaxyEmu.GalaxyEmu( emulator_ID = 4, emulator_version=2, extra = '233Mpc')
#delta sigma [short integration, just for testing!]
emu_ds_test = GalaxyEmu.GalaxyEmu( emulator_ID = 4, emulator_version=2, extra = '30Mpc')

In [14]:
emu_wp.get_clustering(test_param)

array([2.34859058e+02, 1.90084219e+02, 1.47299862e+02, 1.06951314e+02,
       7.20957782e+01, 4.75850650e+01, 3.29640862e+01, 2.37990906e+01,
       1.76233570e+01, 1.25484763e+01, 8.40117614e+00, 5.07069313e+00,
       2.64212583e+00, 1.14658552e+00, 3.80754275e-01, 1.82949979e-01])

In [15]:
# wp expected result:
# array([2.34859058e+02, 1.90084219e+02, 1.47299862e+02, 1.06951314e+02,
#        7.20957782e+01, 4.75850650e+01, 3.29640862e+01, 2.37990906e+01,
#        1.76233570e+01, 1.25484763e+01, 8.40117614e+00, 5.07069313e+00,
#        2.64212583e+00, 1.14658552e+00, 3.80754275e-01, 1.82949979e-01])

In [16]:
emu_xil0.get_clustering(test_param)

array([3.03875389e+01, 2.40689392e+01, 1.87381791e+01, 1.39008809e+01,
       9.77503696e+00, 6.36878680e+00, 3.96354406e+00, 2.39223452e+00,
       1.39744145e+00, 7.54084573e-01, 3.65849027e-01, 1.58462570e-01,
       5.98451964e-02, 1.83905422e-02, 4.11415292e-03, 1.45660840e-03])

In [17]:
# xil0 expected result:
# array([3.03875389e+01, 2.40689392e+01, 1.87381791e+01, 1.39008809e+01,
#        9.77503696e+00, 6.36878680e+00, 3.96354406e+00, 2.39223452e+00,
#        1.39744145e+00, 7.54084573e-01, 3.65849027e-01, 1.58462570e-01,
#        5.98451964e-02, 1.83905422e-02, 4.11415292e-03, 1.45660840e-03])

In [18]:
emu_xil2.get_clustering(test_param)

array([ 1.21559737e+01,  1.19820094e+01,  1.03229586e+01,  8.05673090e+00,
        5.65197911e+00,  3.83744004e+00,  2.16478113e+00,  9.89274304e-01,
        3.20087121e-01, -3.51043688e-03, -1.06055220e-01, -9.62122391e-02,
       -5.91501534e-02, -2.90892043e-02, -1.18425167e-02, -6.47228316e-03])

In [19]:
# xil2 expected result:
# array([ 1.21559737e+01,  1.19820094e+01,  1.03229586e+01,  8.05673090e+00,
#         5.65197911e+00,  3.83744004e+00,  2.16478113e+00,  9.89274304e-01,
#         3.20087121e-01, -3.51043688e-03, -1.06055220e-01, -9.62122391e-02,
#        -5.91501534e-02, -2.90892043e-02, -1.18425167e-02, -6.47228316e-03])

In [20]:
emu_xil4.get_clustering(test_param)

array([6.88000892e+00, 7.98498488e+00, 7.52403613e+00, 6.33204156e+00,
       4.93895494e+00, 3.42781675e+00, 2.22776830e+00, 1.28895715e+00,
       6.25819768e-01, 2.44432467e-01, 7.30657802e-02, 1.76787142e-02,
       5.27700780e-03, 2.98341550e-03, 1.22039993e-03, 1.17837880e-03])

In [21]:
# xil4 expected result:
# array([6.88000892e+00, 7.98498488e+00, 7.52403613e+00, 6.33204156e+00,
#        4.93895494e+00, 3.42781675e+00, 2.22776830e+00, 1.28895715e+00,
#        6.25819768e-01, 2.44432467e-01, 7.30657802e-02, 1.76787142e-02,
#        5.27700780e-03, 2.98341550e-03, 1.22039993e-03, 1.17837880e-03])

In [22]:
emu_ds.get_clustering(test_param)

array([7.72557189e+12, 5.45094697e+12, 3.97762626e+12, 3.01046088e+12,
       2.27212723e+12, 1.62193630e+12, 1.07803559e+12, 7.19953952e+11,
       5.07295162e+11, 3.80122295e+11, 2.90193566e+11, 2.17662506e+11,
       1.51538149e+11])

In [23]:
# ds expected result:
# array([7.72557189e+12, 5.45094697e+12, 3.97762626e+12, 3.01046088e+12,
#        2.27212723e+12, 1.62193630e+12, 1.07803559e+12, 7.19953952e+11,
#        5.07295162e+11, 3.80122295e+11, 2.90193566e+11, 2.17662506e+11,
#        1.51538149e+11])

In [24]:
emu_ds_test.get_clustering(test_param)/emu_ds.get_clustering(test_param)

array([1.018577  , 1.02692385, 1.01574848, 0.99622984, 0.98215442,
       0.97810519, 0.98423551, 0.98226355, 0.98597432, 0.98451047,
       0.98043677, 0.95761996, 0.92318993])

In [25]:
# Impact of using a smaller integration range

In [26]:
emu_ds.r

array([ 0.12589254,  0.19952623,  0.31622777,  0.50118723,  0.79432823,
        1.25892541,  1.99526231,  3.16227766,  5.01187234,  7.94328235,
       12.58925412, 19.95262315, 31.6227766 ])

In [27]:
emu_xil0.r

array([ 0.12485093,  0.19461458,  0.30336044,  0.47287084,  0.7370995 ,
        1.14897266,  1.79099048,  2.79175214,  4.35171493,  6.78334677,
       10.573715  , 16.48204826, 25.69181359, 40.04777049, 62.42548487,
       81.39286209])

In [28]:
#Values of 'r' (computed as the mean of the logarithmic values of rbin edges), 
#the emulator can interpolate (see PSO example) automatically between these values